### PR TITLE
Enable working TLS to smtp.office365.com

### PR DESCRIPTION
**Pull request by Mike221002**
To avoid the error:
app_1  | Traceback (most recent call last):
app_1  |   File "/app/notifiers/smtp.py", line 38, in __init__
app_1  |     self._connect()
app_1  |   File "/app/notifiers/smtp.py", line 53, in _connect
app_1  |     self.server = smtplib.SMTP_SSL(self.host, self.port)
app_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 1050, in __init__
app_1  |     SMTP.__init__(self, host, port, local_hostname, timeout,
app_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 255, in __init__
app_1  |     (code, msg) = self.connect(host, port)
app_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 341, in connect
app_1  |     self.sock = self._get_socket(host, port, self.timeout)
app_1  |   File "/usr/local/lib/python3.9/smtplib.py", line 1057, in _get_socket
app_1  |     new_socket = self.context.wrap_socket(new_socket,
app_1  |   File "/usr/local/lib/python3.9/ssl.py", line 501, in wrap_socket
app_1  |     return self.sslsocket_class._create(
app_1  |   File "/usr/local/lib/python3.9/ssl.py", line 1041, in _create
app_1  |     self.do_handshake()
app_1  |   File "/usr/local/lib/python3.9/ssl.py", line 1310, in do_handshake
app_1  |     self._sslobj.do_handshake()
app_1  | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
app_1  |
app_1  | During handling of the above exception, another exception occurred:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/app/scanner.py", line 246, in <module>
app_1  |     main()
app_1  |   File "/app/scanner.py", line 231, in main
app_1  |     scanner = Scanner()
app_1  |   File "/app/scanner.py", line 74, in __init__
app_1  |     self.notifiers = Notifiers(self.config)
app_1  |   File "/app/notifiers/__init__.py", line 15, in __init__
app_1  |     self.smtp = SMTP(config)
app_1  |   File "/app/notifiers/smtp.py", line 40, in __init__
app_1  |     raise SMTPConfigurationError(exc.message) from exc
app_1  | AttributeError: 'ssl.SSLError' object has no attribute 'message'
tgtg_app_1 exited with code 1

### CODE REVIEW

**Comment by Der-Henning** [comment]
Hi @Mike221002.
Thank you for your contribution! Didn't see this obvious mistake in confusing TLS and SSL...
I guess we need a config option for each TLS and SSL. I will create a code review tomorrow.

**Comment by Der-Henning** [comment]
Can you confirm it is working for you with the changes I made? Note the new TLS and SSL settings in the config.ini.

**Comment by Mike221002** [comment]
I can confirm that the change work fine. Thank you for your fast change.

**Comment by Der-Henning** [comment]
Thank you. I will merge to main and create a new release tomorrow.

**Pull request merged**
